# Copyright 2017, Google, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START app_yaml]
runtime: nodejs
env: flex

# [START env]
env_variables:

  CLOUD_BUCKET: 'titanium-flash-171510.appspot.com'
  PROJECT_ID: 'titanium-flash-171510'
  SQL_USER: 'root'
  SQL_PASSWORD: 'nadhukar123'
  SQL_DATABASE: 'database'
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: 'titanium-flash-171510:us-central1:cloudsql007'
  SQL_CLIENT: 'mysql' # either 'pg' or 'mysql' (all lowercase)
  
    MEMCACHE_URL: 'memcached-11094.c1.us-central1-2.gce.cloud.redislabs.com:11094'
  # If you are using a Memcached server with SASL authentiation enabled,
  # fill in these values with your username and password.
  MEMCACHE_USERNAME: 'root'
  MEMCACHE_PASSWORD: 'nadhukar123'
# [END env]

# [START cloudsql_settings]
beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: 'titanium-flash-171510:us-central1:cloudsql007'
  
# [END cloudsql_settings]
# [END app_yaml]



